# Pour SonarCloud  (gratuit pour les repos publics)
# Remplacer YOUR_ORG et YOUR_PROJECT par vos valeurs
sonar.organization=YOUR_ORG
sonar.projectKey=YOUR_PROJECT

sonar.projectName=DevOps Task Manager
sonar.projectVersion=1.0

sonar.sources=app
sonar.tests=tests
sonar.language=py
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8
