{
 "title": "Task Manager Dashboard",
 "tags": [
  "taskmanager",
  "flask"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requêtes par seconde",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_total[1m])",
     "legendFormat": "{{method}} {{endpoint}} [{{status}}]"
    }
   ]
  },
  {
   "title": "Latence (p95 / p50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(flask_http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, rate(flask_http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Codes HTTP",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(status) (flask_http_request_total)",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  },
  {
   "title": "Logs applicatifs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"app\"}"
    }
   ]
  }
 ]
}